<a href="https://colab.research.google.com/github/subhobrata/Udacity_Deeplearning_Udacity/blob/master/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper

In [3]:
x = torch.rand(3,2)
x

tensor([[0.8793, 0.7459],
        [0.0201, 0.5077],
        [0.4701, 0.1235]])

In [4]:
type(x)

torch.Tensor

In [6]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
z = x+y
z

tensor([[1.8793, 1.7459],
        [1.0201, 1.5077],
        [1.4701, 1.1235]])

In [8]:
z[0]

tensor([1.8793, 1.7459])

In [9]:
z[:,1:]

tensor([[1.7459],
        [1.5077],
        [1.1235]])

In [10]:
z.add(1)

tensor([[2.8793, 2.7459],
        [2.0201, 2.5077],
        [2.4701, 2.1235]])

In [11]:
z

tensor([[1.8793, 1.7459],
        [1.0201, 1.5077],
        [1.4701, 1.1235]])

In [12]:
z.add_(1)

tensor([[2.8793, 2.7459],
        [2.0201, 2.5077],
        [2.4701, 2.1235]])

In [13]:
z

tensor([[2.8793, 2.7459],
        [2.0201, 2.5077],
        [2.4701, 2.1235]])

In [14]:
z.size()

torch.Size([3, 2])

In [15]:
z.resize_(2,3)

tensor([[2.8793, 2.7459, 2.0201],
        [2.5077, 2.4701, 2.1235]])

In [16]:
z

tensor([[2.8793, 2.7459, 2.0201],
        [2.5077, 2.4701, 2.1235]])

In [0]:
a = np.random.rand(4,3)

In [18]:
a

array([[0.50541896, 0.31887205, 0.2672911 ],
       [0.43119533, 0.33207212, 0.05416746],
       [0.90438237, 0.16610458, 0.48486545],
       [0.3529337 , 0.44156931, 0.27132359]])

In [19]:
b = torch.from_numpy(a)
b

tensor([[0.5054, 0.3189, 0.2673],
        [0.4312, 0.3321, 0.0542],
        [0.9044, 0.1661, 0.4849],
        [0.3529, 0.4416, 0.2713]], dtype=torch.float64)

In [20]:
type(b)

torch.Tensor

In [21]:
b.numpy()

array([[0.50541896, 0.31887205, 0.2672911 ],
       [0.43119533, 0.33207212, 0.05416746],
       [0.90438237, 0.16610458, 0.48486545],
       [0.3529337 , 0.44156931, 0.27132359]])

In [22]:
type(b)

torch.Tensor

In [23]:
b.mul_(2)

tensor([[1.0108, 0.6377, 0.5346],
        [0.8624, 0.6641, 0.1083],
        [1.8088, 0.3322, 0.9697],
        [0.7059, 0.8831, 0.5426]], dtype=torch.float64)

In [24]:
a

array([[1.01083792, 0.63774409, 0.5345822 ],
       [0.86239066, 0.66414425, 0.10833492],
       [1.80876474, 0.33220916, 0.9697309 ],
       [0.7058674 , 0.88313861, 0.54264717]])